{ config, pkgs, ... }:

let
  # Per-client launch command, window match and mute/deafen modifiers.
  # Pick the client with DISCORD in modules/home/core/defaults.nix.
  discordClients = {
    concord = {
      launch = "ghostty -e concord";
      window = "title:^(concord)$";
      mods = "ALT";
    };
    vesktop = {
      launch = "vesktop";
      window = "class:^(vesktop)$";
      mods = "CTRL_SHIFT";
    };
  };
  discord = discordClients.${config.home-manager.users.mikel.home.sessionVariables.DISCORD};
in
{
  home-manager.users.mikel = {
    wayland.windowManager.hyprland = {
      enable = true;
      # UWSM owns Hyprland's systemd session integration.
      systemd.enable = false;

      extraConfig = ''
        -- DMS compositor fragments generated by `dms setup`.
        require("dms.colors")
        require("dms.layout")
        require("dms.outputs")
        require("dms.cursor")
        require("dms.windowrules")
        require("dms.binds")

        -- Optional: avoid pixelated XWayland apps on the 4K monitor.
        -- Affects all XWayland apps; each must handle its own scaling.
        -- ONLYOFFICE --force-scale=1.5 also stays at 150% on the 1080p monitor.
        -- hl.config({ xwayland = { force_zero_scaling = true } })

        hl.config({
          input = {
            kb_layout = "us",
            kb_variant = "intl",
          },
        })

        -- Open the configured Discord client.
        hl.bind("SUPER + SHIFT + V", hl.dsp.exec_cmd("${discord.launch}"))
        -- Open the default browser on a blank page.
        hl.bind("SUPER + B", hl.dsp.exec_cmd("xdg-open about:blank"))
        -- Open the editor selected by the user's environment.
        hl.bind("SUPER + C", hl.dsp.exec_cmd("${config.home-manager.users.mikel.home.sessionVariables.EDITOR}"))
        -- Open WhatsApp in ZapFast.
        hl.bind("SUPER + SHIFT + Z", hl.dsp.exec_cmd("zapfast"))

        -- Toggle Handy on press and release so Ctrl+Shift+Space behaves as
        -- push-to-talk. The CLI works reliably with the running instance.
        hl.bind("CTRL + SHIFT + SPACE", hl.dsp.exec_cmd("${pkgs.handy}/bin/handy --toggle-transcription"))
        hl.bind("CTRL + SHIFT + SPACE", hl.dsp.exec_cmd("${pkgs.handy}/bin/handy --toggle-transcription"), { release = true })

        -- Toggle microphone and speaker mute, independent of hardware media keys.
        hl.bind("SUPER + SHIFT + M", hl.dsp.exec_cmd("${pkgs.wireplumber}/bin/wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"))
        hl.bind("SUPER + SHIFT + D", hl.dsp.exec_cmd("${pkgs.wireplumber}/bin/wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))

        -- Forward mute/deafen shortcuts to the selected Discord client.
        hl.bind("SUPER + ALT + M", hl.dsp.send_shortcut({ mods = "${discord.mods}", key = "m", window = "${discord.window}" }))
        hl.bind("SUPER + ALT + D", hl.dsp.send_shortcut({ mods = "${discord.mods}", key = "d", window = "${discord.window}" }))

        -- Capture and annotate a selected region with Quick Capture.
        hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("dms screenshot"))


      '';
    };
  };
}
