{ inputs, pkgs, ... }:

{
  home-manager.users.mikel = {
    imports = [
      "${inputs.home-manager}/modules/services/window-managers/hyprland"
    ];

    wayland.windowManager.hyprland = {
      enable = true;
      systemd.enable = true;

      extraConfig = ''
        -- DMS compositor fragments generated by `dms setup`.
        require("dms.colors")
        require("dms.layout")
        require("dms.outputs")
        require("dms.cursor")

        -- Use an installed cursor theme and avoid hardware-cursor flicker.
        hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")
        hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
        hl.env("HYPRCURSOR_SIZE", "24")
        hl.env("XCURSOR_SIZE", "24")

        hl.config({
          cursor = {
            no_hardware_cursors = 1,
          },
          input = {
            kb_layout = "us",
            kb_variant = "intl",
          },
        })

        require("dms.binds")

        -- Open the default graphical file manager for the home directory.
        hl.bind("SUPER + E", hl.dsp.exec_cmd("xdg-open ~"))
        -- Open the default browser on a blank page.
        hl.bind("SUPER + B", hl.dsp.exec_cmd("xdg-open about:blank"))
        -- Open the editor selected by the user's environment.
        hl.bind("SUPER + C", hl.dsp.exec_cmd("sh -lc 'exec \"$EDITOR\"'"))

        -- Toggle Handy on press and release so Ctrl+Space behaves as
        -- push-to-talk. The CLI works reliably with the running instance.
        hl.bind("CTRL + SPACE", hl.dsp.exec_cmd("${pkgs.handy}/bin/handy --toggle-transcription"))
        hl.bind("CTRL + SPACE", hl.dsp.exec_cmd("${pkgs.handy}/bin/handy --toggle-transcription"), { release = true })

        -- Capture and annotate a selected region with Quick Capture.
        hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("dms ipc call quickCapture screenshot region edit"))

        require("dms.windowrules")

        hl.layer_rule({ match = { namespace = "dms" }, no_anim = true })

      '';
    };
  };
}
