{ pkgs, ... }:

{
  home-manager.users.mikel = {
    qt = {
      enable = true;
      platformTheme.name = "kde";
      style.name = "breeze";
      kde.settings = {
        kdeglobals.Icons.Theme = "Colloid-Dark";
        # Select the palette generated by DMS without managing its contents.
        dolphinrc.UiSettings.ColorScheme = "DankMatugen";
      };
    };

    home.packages = [ pkgs.colloid-icon-theme ];
  };
}
