{ config, pkgs, ... }:

let
  # Dolphin sets cwd but passes no args; Ghostty opens in ~ unless told the
  # directory explicitly. Default terminal comes from defaults.nix.
  terminal = pkgs.writeShellScript "dolphin-terminal" ''
    exec ${config.home-manager.users.mikel.home.sessionVariables.TERMINAL} \
      --working-directory="$PWD" "$@"
  '';
in
{
  home-manager.users.mikel = {
    qt = {
      enable = true;
      # DMS manages ~/.config/qtengine/config.json for dynamic colors and icons.
      platformTheme = {
        name = "qtengine";
        package = pkgs.qtengine;
      };
      # Keep Breeze for both Qt5 and Qt6 independently of the generated config.
      style.name = "breeze";
      kde.settings = {
        kdeglobals.Icons.Theme = "Colloid-Dark";
        # Dolphin "Open Terminal Here" defaults to konsole, which isn't installed.
        kdeglobals.General.TerminalApplication = "${terminal}";
        # Select the palette generated by DMS without managing its contents.
        dolphinrc.UiSettings.ColorScheme = "DankMatugen";
      };
    };

    home.packages = [ pkgs.colloid-icon-theme ];
  };
}
